[relaychain]

default_command = "../target/release/polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

  [[relaychain.nodes]]
  name = "charlie"

  [[relaychain.nodes]]
  name = "dave"

[[parachains]]
id = 1000
cumulus_based = true

  [parachains.collator]
  name = "parachain-A-1000-collator01"
  command = "../target/release/parachain-template-node-two"
    args = [
		"-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace"
	]

[[parachains]]
id = 1001
cumulus_based = true

  [parachains.collator]
  name = "parachain-A-1001-collator01"
  command = "../target/release/parachain-template-node-two"
  args = [
		"-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace"
	]